services:
  deathroom-server:
    image: ghcr.io/${GITHUB_REPOSITORY,,}/server:latest
    container_name: deathroom-server
    ports:
      - "9050:9050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped