name: Server CI

on:
  push:
    branches: [dev]
    paths:
      - 'server/**'
  pull_request:
    branches: [dev]
    paths:
      - 'server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore server/DeathRoom.Server.sln

      - name: Build
        run: dotnet build server/DeathRoom.Server.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test server/DeathRoom.Server.sln --configuration Release --no-build

      - name: Publish Artifacts
        run: dotnet publish server/DeathRoom.Server/DeathRoom.Server.csproj -c Release -o publish
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: publish
