name: Unity Client CI

on:
  push:
    branches: [dev]
    paths:
      - 'client/**'
  pull_request:
    branches: [dev]
    paths:
      - 'client/**'

jobs:
  build:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Build Unity Project
        uses: game-ci/unity-builder@v3
        with:
          targetPlatform: Win64
          projectPath: client

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Run Tests
        uses: game-ci/unity-test-runner@v3
        with:
          projectPath: client
